### ISSUE TITLE
Suggest properties from json schema

### ISSUE THREAD

**Issue by popstas** [adamvoss/vscode-yaml-languageservice#8]
Hello, just tried to add schema for my own yaml config format, hover descriptions works, great!

But can it suggest me properties when I begin typing? Ctrl+Space suggests only words from current yaml.

**Comment by adamvoss** [comment]
See also adamvoss/vscode-yaml#5.  I hope to have a solution to this in the near future.

**Comment by JPinkney** [comment]
@popstas We have this feature implemented in https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml if you'd like to try it out.

**Comment by popstas** [comment]
@JPinkney, great, thank you!
